name: 'Validate Conventional Commits PR'
description: 'Validates that a pull request follows conventional commits. If there is only one commit on the pull request, the commit message will be validated as well, and you may need to amend your commit message.'
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: amannn/action-semantic-pull-request@v5
      with:
        types: |
          fix
          feat
          chore
          docs
        validateSingleCommit: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
